### ISSUE TITLE
Any plan to release models for other tasks?

### ISSUE THREAD

**Issue by quqixun** [IDEA-Research/HumanArt#2]
Will you release models for other tasks (Human Mesh Recovery, Text2Image Generation and Pose&Text2Image Generation) ?

**Comment by juxuan27** [comment]
Hi, @quqixun ! Thank you for your focus.

For Human Mesh Recovery, you can refer to Sketch2Pose model [here](https://github.com/kbrodt/sketch2pose). For Text2Image, please refer to Stable Diffusion [here](https://github.com/Stability-AI/stablediffusion). For Pose&Text2Image, please refer to HumanSD [here](https://github.com/IDEA-Research/HumanSD).
