### ISSUE TITLE
hi, can't find weight

### ISSUE THREAD

**Issue by zht8506** [IDEA-Research/HumanArt#3]
hello, i can not find the weight of "pose_hrnet_w48"? Where can i get it? thanks.

**Comment by juxuan27** [comment]
Hi, @zht8506 ! Thank you for your focus. We now have an active update on [MMPose](https://github.com/open-mmlab/mmpose) and will shortly update this repo to simply link to main branch of MMpose.
As for the weights, you can find them here: https://github.com/open-mmlab/mmpose/tree/dev-1.x . More specifically, https://github.com/open-mmlab/mmpose/blob/dev-1.x/configs/body_2d_keypoint/rtmpose/humanart/rtmpose_humanart.md , https://github.com/open-mmlab/mmpose/blob/dev-1.x/configs/body_2d_keypoint/topdown_heatmap/humanart/hrnet_humanart.md , https://github.com/open-mmlab/mmpose/blob/dev-1.x/configs/body_2d_keypoint/topdown_heatmap/humanart/vitpose_humanart.md .

**Comment by zht8506** [comment]
This helped me. Thank you very much for your reply!
