### ISSUE TITLE
no faster_rcnn_r50_fpn_1x_humanart config in mmdetection repo

### ISSUE THREAD

**Issue by Citalopram-wyc** [IDEA-Research/HumanArt#5]

**Comment by juxuan27** [comment]
Hi, @Citalopram-wyc .Thank you for your focus.
Here it is: https://github.com/juxuan27/mmdetection/blob/bdf2f272d94c79563f67f649915114ee09b6a1ff/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_humanart.py
