### ISSUE TITLE
problem in download dataset

### ISSUE THREAD

**Issue by xinsir6** [IDEA-Research/HumanArt#6]
![image](https://github.com/IDEA-Research/HumanArt/assets/128811208/4d4e3947-afec-4399-ab80-606ec8618dd0)
hi，I try to download the 8G file multiple times, but it always failed when it come close to finish, and I can't continue to download from where it stop, so can you split the file into 2 smaller one, because the internet speed is not really good in china, thank you

**Comment by juxuan27** [comment]
Hi, @xinsir6 . Thank you for your focus.
I think there are ways to continue download from where it stop in Google Drive and you can search it in google. But if it is still a trouble for you, you can give me your email and I will send Baidu Netdisk link for you.

**Comment by xinsir6** [comment]
Thank you very much, I have send a email to you, and you can check it out, that's my email.
