### ISSUE TITLE
question about the experiment result

### ISSUE THREAD

**Issue by xinsir6** [IDEA-Research/HumanArt#7]
![image](https://github.com/IDEA-Research/HumanArt/assets/128811208/8ee619ca-3e87-4151-83bb-d1195c2f4223)
hi, I see that you report the human skeleton detection result about ED_pose，however，it is unclear about whether it uses the ground truch bounding-box, indeed 72.3AP on human-art is a very high baseline(if it doesn't use the ground truth bounding box) and the methods in mmpose rarely reach, ED_pose is an end2end method，so I think it will be better if you can explain it. Any way, I want to ask if the human art data can be directly used in ED_pose training code, anything else need to be adjusted?

**Comment by juxuan27** [comment]
We do not use ground truth bbox for ED-Pose. It is a one-stage method thus it is hard to use ground truth bbox in its method. My explanation for this is that ED-Pose can learn a better bounding-box (which top-down methods can not) as well as a better keypoint position, which leads to a high AP.
You can directly use ED-Pose's code to train and test Human-Art. But you need to change the path for config file and data path (for images) in its code (only a few lines adjustment).

**Comment by xinsir6** [comment]
hello，I have used the model you provided about ED-pose to test on some unlabeled images，but the original ed-pose does not provide a inference scripts, I write a inference scripts based on the evaluation process but lack some hyper parameter, I post my problem in https://github.com/IDEA-Research/ED-Pose/issues/15, no one reply sadly. I just want to recover the end-2-end ED-pose precision on HumanArt， and use the model to make tags. Could you please give some help? Provide a inference scripts based on the ed-pose, the result I write by myself is far away from the result posted.

**Comment by juxuan27** [comment]
Hi, @xinsir6 . I have asked the author of ED-Pose to upload a inference script on GitHub. Please keep an eye to the ED-Pose repo.
