### ISSUE TITLE
Broken Links in Docs

### ISSUE THREAD

**Issue by isobelm** [IDEA-Research/HumanArt#8]
Hi,

These links don't seem to work, are these files available?

These are the links for the pose detection models.

<img width="677" alt="Screenshot 2023-08-12 at 2 04 49 p m" src="https://github.com/IDEA-Research/HumanArt/assets/34947052/f5ce00d1-581e-4025-8300-bb8a2f50331d">

**Comment by fjenett** [comment]
Anyone found the correct link?

**Comment by fjenett** [comment]
`https://drive.google.com/file/d/1gs1RCxRcItUHwA5N8P5_9mKcgwLiBjOO/view?usp=share_link` is not valid or not set to be public.

**Comment by juxuan27** [comment]
Hi, @fjenett and @isobelm ! Sorry for the late reply. We have supported our model in MMPose and you can refer to the updated readme for new models. Thank you for your focus!
